### ISSUE TITLE
Rez pip install package errors and warnings on Linux

### ISSUE THREAD

**Issue by johhnry** [ArtFXDev/silex_client#88]
Using `Rez 2.100.0` and commit 1fc378b trying to install the package locally:

```bash
$ rez pip -i .
```

Everything is working well but I have the warnings:

```
21:49:20 WARNING  Metadata: missing: ['Author'], warnings: []
21:49:20 WARNING  Metadata: missing: ['Home-page', 'Author'], warnings: []
21:49:21 WARNING  Ignoring extras requested on 'python-socketio[client]==5.4.0' - this is not yet supported
```

And this error:

```
Traceback (most recent call last):
  File "/home/josephhenry/rez/bin/rez/rez", line 8, in <module>
    sys.exit(run_rez())
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/cli/_entry_points.py", line 80, in run_rez
    return run()
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/cli/_main.py", line 202, in run
    returncode = run_cmd()
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/cli/_main.py", line 194, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/cli/pip.py", line 84, in command
    extra_args=opts.extra)
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/pip.py", line 357, in pip_install_package
    name_casings=dist_names
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/utils/pip.py", line 396, in get_rez_requirements
    is_pure_python = is_pure_python_package(installed_dist)
  File "/home/josephhenry/rez/lib/python3.7/site-packages/rez/utils/pip.py", line 338, in is_pure_python_package
    wheel_data = setuptools_dist.get_metadata('WHEEL')
AttributeError: 'NoneType' object has no attribute 'get_metadata'
```

The error might be due to the missing `tractor` package but we need to make a package out of this.

Then if I try to run the env with `silex_client`, I get the following:

```
$ rez env silex_client
21:57:30 ERROR    PackageFamilyNotFoundError: package family not found: typing_extensions, was required by: aiohttp (searched: /home/josephhenry/packages; /home/josephhenry/.rez/packages/int; /home/josephhenry/.rez/packages/ext)
```

Finally trying to install `typing_extensions` with rez-pip gives me an error:

=> Here is the related issue: https://github.com/nerdvegas/rez/issues/1159#issue-1063846767

I am running `Python 3.7.9` on `Linux pop-os 5.13.0-7620-generic`

**Comment by johhnry** [comment]
It works now with the latest fixes from Rez (`v2.103.1`): https://github.com/nerdvegas/rez/commit/5c6c8eb78beb02fe8902d39e313cceafb8a0bd66

I was able to do `rez pip -i .` from `silex_client` and then `rez env silex_client` successfully!
